# Generated by Django 3.0.5 on 2020-05-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='Album',
        ),
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='songs',
            new_name='Song',
        ),
    ]
